version: '3.8'

services:
  api-service:
    build: ./api-service
    ports:
      - "5000:5000"
    depends_on:
      - database
    environment:
      - DATABASE_URL=postgresql://user:password@database:5432/mydb

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - api-service

  auth-service:
    build: ./auth-service
    ports:
      - "5001:5001"

  database:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
